<?php

namespace AppBundle\Repository;

/**
 * SentenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentenceRepository extends \Doctrine\ORM\EntityRepository
{
}
