<?php

namespace AppBundle\Repository;

/**
 * SentenceCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentenceCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
