<?php

namespace AppBundle\Repository;

/**
 * SentenceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentenceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
