<?php

namespace AppBundle\Repository;

/**
 * SentenceWordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SentenceWordRepository extends \Doctrine\ORM\EntityRepository
{
}
