<?php

namespace AppBundle\Repository;

/**
 * SpeechCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpeechCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
