<?php

namespace AppBundle\Repository;

/**
 * WebsocketLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsocketLogRepository extends \Doctrine\ORM\EntityRepository
{
}
