<?php

namespace AppBundle\Repository;

/**
 * WordTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WordTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
