<?php

namespace AppBundle\Repository;

/**
 * WsMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WsMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
